services:
  postgres:
    image: postgres:16
    container_name: drogon_pg
    restart: unless-stopped
    environment:
      POSTGRES_USER: dragon
      POSTGRES_PASSWORD: dragonpass
      POSTGRES_DB: dragon_clans
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: clan_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
